Type Numerical Action
fdw/rofimoji pull request #213
Opened 2024-12-27 23:41 UTC by relma2

Added a `type-numerical` action to rofimoji that uses the typer to type `Ctrl+Shift+U+<unicode>` to enter an emoji by its unicode codepoint directly.

I still need help implementing the typer functions. I don't have the compositor for wtype, so I just guessed how it works, and I still have a bug entering the unicodes in xdotool.

2024-12-28 16:05 UTC, relma2 commented
@fdw Please take a look and help me with testing `wtype`

2025-01-06 00:07 UTC, relma2 commented
@fdw please look at my PR

2025-01-16 16:42 UTC, fdw requested changes
Sorry for the wait!

Looking good so far, just some smaller comments left.

2025-01-16 16:42 UTC, fdw commented on README.md
> +| `--action`                                                                                                              | `-a`         | `type`, `type-numerical`, `copy`, `clipboard`, `unicode`, `c
This is not as important as `copy`; I'd move it after `clipboard`.

2025-01-16 16:42 UTC, fdw commented on src/picker/argument_parsing.py
> +        default="Alt+n",
Do you think this is used often enough to warrant a default keybinding?

2025-01-16 16:42 UTC, fdw commented on src/picker/typer/xdotool.py
> +                    "--clearmodifiers",
This should probably be something like `key ctrl+shift+u type codepoints` without the loop.

2025-03-13 02:47 UTC, relma2 commented on src/picker/argument_parsing.py
> +        default="Alt+n",
yeah i think so. i just followed the pattern of the other actions

2025-03-13 02:49 UTC, relma2 commented on src/picker/typer/xdotool.py
> +                    "--clearmodifiers",
the loop is because there might be multiple emojis being passed into characters

2025-03-13 02:50 UTC, relma2 commented
@fdw sorry for the delay; life got in the way, bu now i am ready to move forward on this PR

2025-03-23 09:22 UTC, fdw requested changes
Sorry for the wait; you caught me at a busy time.

Looking good so far, thank you

2025-03-23 09:22 UTC, fdw commented on src/picker/argument_parsing.py
> +        default="Alt+n",
Fair enough

2025-03-23 09:22 UTC, fdw commented on src/picker/typer/wtype.py
> +            print(["wtype", "-M", "ctrl"," -M", "shift", "-k", "u"] + [f for p in unicode_codepoint for f in ("-k", p)] + ["-m", "ctrl", "-m", "shift"])
Is this supposed to be here?

2025-03-23 09:22 UTC, fdw commented on src/picker/typer/xdotool.py
> +                    "--clearmodifiers",
Then I'd rather iterate over `characters` instead of the codepoints, like in `wtype.py`. And then one call to `run` for the whole codepoint, because we need to pass all of it with `Ctrl+Shift+U`.

2025-03-23 09:22 UTC, fdw commented on README.md
> +| `type-numerical`| `alt+n` | Directly type the emoji(s) by using their Unicode codepoints; this simulates Ctrl+Shift+U<codepoint> on the keyboard              |
Could you please here also move it after `clipboard` so that it's the same order all the time?

2025-03-23 20:46 UTC, relma2 commented on src/picker/typer/xdotool.py
> +                    "--clearmodifiers",
iterated over chartacters

2025-03-23 20:47 UTC, relma2 commented on src/picker/typer/wtype.py
> +            print(["wtype", "-M", "ctrl"," -M", "shift", "-k", "u"] + [f for p in unicode_codepoint for f in ("-k", p)] + ["-m", "ctrl", "-m", "shift"])
nope!

2025-03-23 20:47 UTC, relma2 commented on README.md
> +| `type-numerical`| `alt+n` | Directly type the emoji(s) by using their Unicode codepoints; this simulates Ctrl+Shift+U<codepoint> on the keyboard              |
moved

2025-03-29 10:25 UTC, fdw requested changes
Oh, and could you please `rebase` onto `main` instead of merging? The diff is quite confusing and the history doesn't look better, either.

Thank you!

2025-03-29 10:25 UTC, fdw commented on README.md
> +| `--keybinding-copy`, `--keybinding-type`, `--keybinding-clipboard`, `--keybinding-unicode`, `--keybinding-copy-unicode`, `--keybinding-type-numerical` |              |
Here, too, it should be before `unicode`

2025-03-29 10:25 UTC, fdw commented on src/picker/action.py
> +        elif action == Action.TYPE_NUMERICAL:
Please also move it before `COPY_UNICODE` here. It should be same exact order everywhere, otherwise it gets confusing.

2025-03-29 10:25 UTC, fdw commented on src/picker/selector/rofi.py
> +            "-kb-custom-16",
These need to be moved up as well

2025-03-29 10:25 UTC, fdw commented on src/picker/typer/wtype.py
> +            for codepoint in codepoints:
This doesn't really work for me. What does is using the same code you've written for `xdotool`:
```
            unicode_codepoints = get_codepoints(character)
            codepoint_list = unicode_codepoints.split("-")
            codepoint_list = ["U" + codepoint for codepoint in codepoint_list]
            codepoint_list = " ".join(codepoint_list)

            run(["wtype", "-M", "ctrl", "-M", "shift", codepoint_list, "-m", "ctrl", "-m", "shift"])
```

2025-03-31 05:44 UTC, relma2 commented on README.md
> +| `--keybinding-copy`, `--keybinding-type`, `--keybinding-clipboard`, `--keybinding-unicode`, `--keybinding-copy-unicode`, `--keybinding-type-numerical` |              |
done

2025-03-31 05:44 UTC, relma2 commented on src/picker/typer/wtype.py
> +            for codepoint in codepoints:
amended code

2025-03-31 05:45 UTC, relma2 commented on src/picker/selector/rofi.py
> +            "-kb-custom-16",
moved up

2025-03-31 05:47 UTC, relma2 commented
Squashed commits; also the **rofi** picker is invisible on my laptop; I think this is a rofi bug

2025-03-31 17:03 UTC, merged

2025-03-31 17:03 UTC, fdw commented
Awesome, thank you very much!